In [61]:
!git clone 'https://github.com/HarshvardhanSingh-13/Datasets'

fatal: destination path 'Datasets' already exists and is not an empty directory.

# 1) Overall Data Exploration

In [62]:
import pandas as pd
import numpy as np

In [63]:
df=pd.read_csv('/content/Datasets/Airbnb/airbnb_v2.csv')

In [64]:
df

,Unnamed: 0,id,name,rating,reviews,host_name,host_id,address,features,amenities,...,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
0,0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...",...,8078,Turkey,1,1,2,0,2,0,Flexible,12 00 pm
1,1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,4665,Turkey,2,2,4,0,2,0,4 00 pm - 11 00 pm,10 00 am
2,2,50699164,cottages sataplia,4.85,68,Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...",...,5991,Georgia,1,3,4,0,1,0,After 1 00 pm,12 00 pm
3,3,49871422,Sapanca Breathable Bungalow,5.0,13,Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...",...,11339,Turkey,1,2,4,0,1,0,After 2 00 pm,12 00 pm
4,4,51245886,Bungalov Ev 2,New,0,Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...",...,6673,Turkey,1,1,2,0,1,0,After 2 00 pm,12 00 pm
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12800,12800,44697740,"Brown Dome House No. 3, full of healing",4.94,16,Aidan,161552316.0,"Imhoe-myeon, Jindo, South Jeolla Province, Sou...","4 guests,8 bathrooms","Kitchen,Wifi,Free parking on premises,Private ...",...,4288,South Korea,8,0,4,0,0,0,3 00 pm - 11 00 pm,11 00 am
12801,12801,29975283,Bubble Hotel Ubud with Bathtub under the Sky,4.67,6,Martha,118954227.0,"Gianyar, Indonesia","2 guests,1 bedroom,1 bed,Toilet with sink","Wifi,Free on-street parking,Air conditioning,G...",...,15200,Indonesia,0,1,2,1,1,0,3 00 pm - 10 00 pm,12 00 pm
12802,12802,32977697,Paradise Eco Hub,4.67,3,Silas,175214568.0,"Kabale, Uganda","2 guests,1 bedroom,2 beds,1 private bathroom","Wifi,Breakfast,Long-term stays allowed,Unavail...",...,9103,Uganda,1,2,2,0,1,0,After 3 00 pm,NaN
12803,12803,8006146,WisDOME - Mentigi Bay Village - Gilis - Lombok,4.86,7,Cempaka,718423.0,"Gunung Sari, Nusa Tenggara Barat, Indonesia","8 guests,2 bedrooms,4 beds,2.5 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,42262,Indonesia,2,4,8,0,2,0,Flexible,12 00 pm
12804,12804,40547903,Enjoy Vitamin SEA! Ocean Front! [Ocean's Seven],4.85,13,Achy,246470880.0,"Uruma, Okinawa, Japan","5 guests,1 bedroom,2 beds,1 bathroom","Sea view,Beach access – Beachfront,Kitchen,Wif...",...,9909,Japan,1,2,5,0,1,0,After 4 00 pm,11 00 am

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12805 entries, 0 to 12804
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    12805 non-null  int64
 1   id            12805 non-null  int64
 2   name          12805 non-null  object
 3   rating        12805 non-null  object
 4   reviews       12805 non-null  object
 5   host_name     12797 non-null  object
 6   host_id       12805 non-null  float64
 7   address       12805 non-null  object
 8   features      12805 non-null  object
 9   amenities     12805 non-null  object
 10  safety_rules  12805 non-null  object
 11  hourse_rules  12805 non-null  object
 12  img_links     12805 non-null  object
 13  price         12805 non-null  int64
 14  country       12805 non-null  object
 15  bathrooms     12805 non-null  int64
 16  beds          12805 non-null  int64
 17  guests        12805 non-null  int64
 18  toiles        12805 non-null  int64
 19  bedrooms      12805 non-null  int64
 20  studios       12805 non-null  int64
 21  checkin       12005 non-null  object
 22  checkout      10355 non-null  object
dtypes: float64(1), int64(9), object(13)
memory usage: 2.2+ MB

In [66]:
df.describe()

,Unnamed: 0,id,host_id,price,bathrooms,beds,guests,toiles,bedrooms,studios
count,12805.000000,1.280500e+04,1.280500e+04,1.280500e+04,12805.000000,12805.000000,12805.000000,12805.000000,12805.000000,12805.000000
mean,6402.000000,7.525187e+16,1.638192e+08,1.769780e+04,1.874424,3.316751,5.213745,0.019211,2.136041,0.023585
std,3696.629433,2.007933e+17,1.413622e+08,4.569364e+04,2.091399,4.037791,3.808830,0.137272,2.359005,0.151757
min,0.000000,1.313100e+04,2.303900e+04,3.930000e+02,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,3201.000000,2.023958e+07,3.700032e+07,3.994000e+03,1.000000,1.000000,2.000000,0.000000,1.000000,0.000000
50%,6402.000000,3.682229e+07,1.256459e+08,8.175000e+03,1.000000,2.000000,4.000000,0.000000,1.000000,0.000000
75%,9603.000000,4.999760e+07,2.639623e+08,1.606200e+04,2.000000,4.000000,6.000000,0.000000,3.000000,0.000000
max,12804.000000,7.017905e+17,4.758973e+08,1.907963e+06,50.000000,98.000000,16.000000,1.000000,50.000000,1.000000

In [67]:
df['safety_rules']

0        󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...
1        󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...
2        󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...
3        󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...
4        󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...
                               ...
12800    󹀁,Airbnb's COVID-19 safety practices apply,󱠁,C...
12801    󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...
12802    󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...
12803    󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...
12804    󹀁,Airbnb's COVID-19 safety practices apply,󱠃,S...
Name: safety_rules, Length: 12805, dtype: object

In [68]:
df['img_links'][0]

'https://a0.muscache.com/im/pictures/a5da5cb7-cac8-488f-85b1-a0dd78b28a86.jpg?im_w=720 https://a0.muscache.com/im/pictures/9aa4bc71-de8e-444a-b9fa-c2679a71a059.jpg?im_w=720 https://a0.muscache.com/im/pictures/81c2d325-fc04-40da-852f-9490df74b62b.jpg?im_w=720 https://a0.muscache.com/im/pictures/cf7f3f57-8a00-4397-acea-c891760d4b2f.jpg?im_w=720 https://a0.muscache.com/im/pictures/0fc82edc-c539-453b-8a46-268c988530fc.jpg?im_w=720 https://a0.muscache.com/im/pictures/54e427bb-9cb7-4a81-94cf-78f19156faad.jpg'

In [69]:
df.head(2)

,Unnamed: 0,id,name,rating,reviews,host_name,host_id,address,features,amenities,...,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
0,0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...",...,8078,Turkey,1,1,2,0,2,0,Flexible,12 00 pm
1,1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,4665,Turkey,2,2,4,0,2,0,4 00 pm - 11 00 pm,10 00 am

In [70]:
df.tail(2)

,Unnamed: 0,id,name,rating,reviews,host_name,host_id,address,features,amenities,...,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
12803,12803,8006146,WisDOME - Mentigi Bay Village - Gilis - Lombok,4.86,7,Cempaka,718423.0,"Gunung Sari, Nusa Tenggara Barat, Indonesia","8 guests,2 bedrooms,4 beds,2.5 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,42262,Indonesia,2,4,8,0,2,0,Flexible,12 00 pm
12804,12804,40547903,Enjoy Vitamin SEA! Ocean Front! [Ocean's Seven],4.85,13,Achy,246470880.0,"Uruma, Okinawa, Japan","5 guests,1 bedroom,2 beds,1 bathroom","Sea view,Beach access – Beachfront,Kitchen,Wif...",...,9909,Japan,1,2,5,0,1,0,After 4 00 pm,11 00 am

In [71]:
df.columns

Index(['Unnamed: 0', 'id', 'name', 'rating', 'reviews', 'host_name', 'host_id',
       'address', 'features', 'amenities', 'safety_rules', 'hourse_rules',
       'img_links', 'price', 'country', 'bathrooms', 'beds', 'guests',
       'toiles', 'bedrooms', 'studios', 'checkin', 'checkout'],
      dtype='object')

In [72]:
df['country'] == 'India'

0        False
1        False
2        False
3        False
4        False
         ...
12800    False
12801    False
12802    False
12803    False
12804    False
Name: country, Length: 12805, dtype: bool

In [73]:
df[df['country'] == 'India']

,Unnamed: 0,id,name,rating,reviews,host_name,host_id,address,features,amenities,...,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
1646,1646,38687195,The Shilaroo Project- a unique mountain homestay,New,2,Shubhangna,224273291.0,India,"5 guests,1 bedroom,5 beds,3 shared bathrooms","Free parking on premises,Bath,Patio or balcony...",...,2054,India,3,5,5,0,1,0,Flexible,12 00 pm
1665,1665,40643691,The Shilaroo Project - a unique mountain homestay,4.88,8,Shubhangna,224273291.0,India,"3 guests,1 bedroom,3 beds,3.5 bathrooms","Dedicated workspace,Free parking on premises,B...",...,1484,India,3,3,3,0,1,0,Flexible,12 00 pm
1671,1671,38829491,The Shilaroo Project - a unique mountain homestay,4.8,10,Shubhangna,224273291.0,India,"2 guests,1 bedroom,1 bed,1 private bathroom","Valley view,Mountain view,Free driveway parkin...",...,6276,India,1,1,2,0,1,0,Flexible,12 00 pm
1810,1810,49052782,Leap Of Nature -Mountain View & Riverside-Home...,4.94,16,Sapna,361663736.0,India,"3 guests,1 bedroom,2 beds,1 private bathroom","Garden view,Mountain view,Waterfront,Wifi,Dedi...",...,3195,India,1,2,3,0,1,0,After 11 00 am,10 00 am
2332,2332,51254294,"Charming, chillout houseboat in great location",New,1,City Ofkashmir,80811491.0,India,"6 guests,3 bedrooms,8 beds,3 bathrooms","Dedicated workspace,Pool,Hot tub,Dryer,Air con...",...,1712,India,3,8,6,0,3,0,After 9 00 am,NaN
2356,2356,13387548,Houseboat shoda palace,New,0,Nasir Ali,76085919.0,India,"2 guests,1 bedroom,1 bed,1 private bathroom","Wifi,Breakfast,Unavailable: Carbon monoxide al...",...,5150,India,1,1,2,0,1,0,NaN,NaN
2364,2364,12919177,"Room in luxury houseboat, Dal Lake",New,0,Riyaz,70867331.0,India,"3 guests,1 bedroom,2 beds,1 bathroom","Wifi,TV with standard cable/satellite,Washing ...",...,4651,India,1,2,3,0,1,0,8 00 am - 2 00 am,12 00 pm
3198,3198,619016314383105343,Heritage Mansion by royal architect- Hillview ...,4.82,11,Padsha,456839385.0,India,"6 guests,1 bedroom,2 beds,1 private bathroom","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,4565,India,1,2,6,0,1,0,After 3 00 pm,NaN
6003,6003,15526157,Renu's Place for Women only,4.98,132,Renu,99834922.0,India,"2 guests,1 bedroom,1 bed,1 private bathroom","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,2096,India,1,1,2,0,1,0,11 00 am - 9 00 pm,10 00 am
6197,6197,48798026,Cozy Comfortable Stay!!!,New,0,Jai Guru Ji,372271238.0,India,"2 guests,1 bedroom,1 bed,1 private bathroom","Wifi,Free parking on premises,TV,Air condition...",...,923,India,1,1,2,0,1,0,11 00 am - 11 00 pm,NaN
6541,6541,677928164637144798,A heritage property nestled next to the lake.,New,2,Paradise Wangnoo,471218443.0,India,"4 guests,19 bedrooms,2 beds,23 shared baths","Garden view,Lake view,Waterfront,Kitchen,Wifi,...",...,2295,India,23,2,4,0,19,0,Flexible,12 00 pm
6661,6661,589394294839217050,Cheerful 2 bedroom set with separate entrance,New,0,Tasaduq,152680179.0,India,"5 guests,2 bedrooms,2 beds,2 shared bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,3356,India,2,2,5,0,2,0,After 3 00 pm,12 00 pm
9705,9705,21115776,Harmony Farm Wayand - Sky High Cottage 1,New,1,Kochuthresia,114940601.0,India,"2 guests,1 bedroom,1 bed,1 bathroom","Mountain view,Garden view,Wifi,Dedicated works...",...,5934,India,1,1,2,0,1,0,2 00 pm - 11 00 pm,11 00 am

In [74]:
df[(df['country'] == 'India') & (df['price'] < 1000)]

,Unnamed: 0,id,name,rating,reviews,host_name,host_id,address,features,amenities,...,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
6197,6197,48798026,Cozy Comfortable Stay!!!,New,0,Jai Guru Ji,372271238.0,India,"2 guests,1 bedroom,1 bed,1 private bathroom","Wifi,Free parking on premises,TV,Air condition...",...,923,India,1,1,2,0,1,0,11 00 am - 11 00 pm,NaN

In [75]:
## Filtered data where country is Turkey and number of bedroom > 1 and the name of owners of first 5

In [76]:
df[(df['country'] == 'Turkey') & (df['bedrooms'] >=1)].head(5)['name']

70                                 Sea View Villa in Kas
5862      (105) King Cave Suite (Mysterious Cave Suites)
5885    (107) Deluxe Cave Suite (Mysterious Cave Suites)
Name: name, dtype: object

In [77]:
## for Japan
df[(df['country'] == 'Japan') & (df['bedrooms'] >=1 )].head(5)['name']

6925    4BD/11PPL Only one group a day - "Casa BUDONO-KI"
Name: name, dtype: object

In [78]:
df['country'].value_counts()

country
 India         2766
 Italy         1186
 Greece         885
 Thailand       677
 Turkey         519
               ...
 Kosovo           1
 Guatemala        1
 St Martin        1
Puerto Rico       1
 Senegal          1
Name: count, Length: 148, dtype: int64

In [79]:
df.isnull().sum()

Unnamed: 0         0
id                 0
name               0
rating             0
reviews            0
host_name          8
host_id            0
address            0
features           0
amenities          0
safety_rules       0
hourse_rules       0
img_links          0
price              0
country            0
bathrooms          0
beds               0
guests             0
toiles             0
bedrooms           0
studios            0
checkin          800
checkout        2450
dtype: int64

In [80]:
df.dropna(subset = 'host_name')

,Unnamed: 0,id,name,rating,reviews,host_name,host_id,address,features,amenities,...,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
0,0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...",...,8078,Turkey,1,1,2,0,2,0,Flexible,12 00 pm
1,1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,4665,Turkey,2,2,4,0,2,0,4 00 pm - 11 00 pm,10 00 am
2,2,50699164,cottages sataplia,4.85,68,Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...",...,5991,Georgia,1,3,4,0,1,0,After 1 00 pm,12 00 pm
3,3,49871422,Sapanca Breathable Bungalow,5.0,13,Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...",...,11339,Turkey,1,2,4,0,1,0,After 2 00 pm,12 00 pm
4,4,51245886,Bungalov Ev 2,New,0,Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...",...,6673,Turkey,1,1,2,0,1,0,After 2 00 pm,12 00 pm
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12800,12800,44697740,"Brown Dome House No. 3, full of healing",4.94,16,Aidan,161552316.0,"Imhoe-myeon, Jindo, South Jeolla Province, Sou...","4 guests,8 bathrooms","Kitchen,Wifi,Free parking on premises,Private ...",...,4288,South Korea,8,0,4,0,0,0,3 00 pm - 11 00 pm,11 00 am
12801,12801,29975283,Bubble Hotel Ubud with Bathtub under the Sky,4.67,6,Martha,118954227.0,"Gianyar, Indonesia","2 guests,1 bedroom,1 bed,Toilet with sink","Wifi,Free on-street parking,Air conditioning,G...",...,15200,Indonesia,0,1,2,1,1,0,3 00 pm - 10 00 pm,12 00 pm
12802,12802,32977697,Paradise Eco Hub,4.67,3,Silas,175214568.0,"Kabale, Uganda","2 guests,1 bedroom,2 beds,1 private bathroom","Wifi,Breakfast,Long-term stays allowed,Unavail...",...,9103,Uganda,1,2,2,0,1,0,After 3 00 pm,NaN
12803,12803,8006146,WisDOME - Mentigi Bay Village - Gilis - Lombok,4.86,7,Cempaka,718423.0,"Gunung Sari, Nusa Tenggara Barat, Indonesia","8 guests,2 bedrooms,4 beds,2.5 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,42262,Indonesia,2,4,8,0,2,0,Flexible,12 00 pm
12804,12804,40547903,Enjoy Vitamin SEA! Ocean Front! [Ocean's Seven],4.85,13,Achy,246470880.0,"Uruma, Okinawa, Japan","5 guests,1 bedroom,2 beds,1 bathroom","Sea view,Beach access – Beachfront,Kitchen,Wif...",...,9909,Japan,1,2,5,0,1,0,After 4 00 pm,11 00 am

# 2) Column Wise Exploration

In [81]:
df

,Unnamed: 0,id,name,rating,reviews,host_name,host_id,address,features,amenities,...,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
0,0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...",...,8078,Turkey,1,1,2,0,2,0,Flexible,12 00 pm
1,1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,4665,Turkey,2,2,4,0,2,0,4 00 pm - 11 00 pm,10 00 am
2,2,50699164,cottages sataplia,4.85,68,Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...",...,5991,Georgia,1,3,4,0,1,0,After 1 00 pm,12 00 pm
3,3,49871422,Sapanca Breathable Bungalow,5.0,13,Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...",...,11339,Turkey,1,2,4,0,1,0,After 2 00 pm,12 00 pm
4,4,51245886,Bungalov Ev 2,New,0,Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...",...,6673,Turkey,1,1,2,0,1,0,After 2 00 pm,12 00 pm
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12800,12800,44697740,"Brown Dome House No. 3, full of healing",4.94,16,Aidan,161552316.0,"Imhoe-myeon, Jindo, South Jeolla Province, Sou...","4 guests,8 bathrooms","Kitchen,Wifi,Free parking on premises,Private ...",...,4288,South Korea,8,0,4,0,0,0,3 00 pm - 11 00 pm,11 00 am
12801,12801,29975283,Bubble Hotel Ubud with Bathtub under the Sky,4.67,6,Martha,118954227.0,"Gianyar, Indonesia","2 guests,1 bedroom,1 bed,Toilet with sink","Wifi,Free on-street parking,Air conditioning,G...",...,15200,Indonesia,0,1,2,1,1,0,3 00 pm - 10 00 pm,12 00 pm
12802,12802,32977697,Paradise Eco Hub,4.67,3,Silas,175214568.0,"Kabale, Uganda","2 guests,1 bedroom,2 beds,1 private bathroom","Wifi,Breakfast,Long-term stays allowed,Unavail...",...,9103,Uganda,1,2,2,0,1,0,After 3 00 pm,NaN
12803,12803,8006146,WisDOME - Mentigi Bay Village - Gilis - Lombok,4.86,7,Cempaka,718423.0,"Gunung Sari, Nusa Tenggara Barat, Indonesia","8 guests,2 bedrooms,4 beds,2.5 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...",...,42262,Indonesia,2,4,8,0,2,0,Flexible,12 00 pm
12804,12804,40547903,Enjoy Vitamin SEA! Ocean Front! [Ocean's Seven],4.85,13,Achy,246470880.0,"Uruma, Okinawa, Japan","5 guests,1 bedroom,2 beds,1 bathroom","Sea view,Beach access – Beachfront,Kitchen,Wif...",...,9909,Japan,1,2,5,0,1,0,After 4 00 pm,11 00 am

In [82]:
del df['Unnamed: 0']

In [83]:
df

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,...,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",...,8078,Turkey,1,1,2,0,2,0,Flexible,12 00 pm
1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,4665,Turkey,2,2,4,0,2,0,4 00 pm - 11 00 pm,10 00 am
2,50699164,cottages sataplia,4.85,68,Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",...,5991,Georgia,1,3,4,0,1,0,After 1 00 pm,12 00 pm
3,49871422,Sapanca Breathable Bungalow,5.0,13,Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",...,11339,Turkey,1,2,4,0,1,0,After 2 00 pm,12 00 pm
4,51245886,Bungalov Ev 2,New,0,Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,6673,Turkey,1,1,2,0,1,0,After 2 00 pm,12 00 pm
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12800,44697740,"Brown Dome House No. 3, full of healing",4.94,16,Aidan,161552316.0,"Imhoe-myeon, Jindo, South Jeolla Province, Sou...","4 guests,8 bathrooms","Kitchen,Wifi,Free parking on premises,Private ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠁,C...",...,4288,South Korea,8,0,4,0,0,0,3 00 pm - 11 00 pm,11 00 am
12801,29975283,Bubble Hotel Ubud with Bathtub under the Sky,4.67,6,Martha,118954227.0,"Gianyar, Indonesia","2 guests,1 bedroom,1 bed,Toilet with sink","Wifi,Free on-street parking,Air conditioning,G...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,15200,Indonesia,0,1,2,1,1,0,3 00 pm - 10 00 pm,12 00 pm
12802,32977697,Paradise Eco Hub,4.67,3,Silas,175214568.0,"Kabale, Uganda","2 guests,1 bedroom,2 beds,1 private bathroom","Wifi,Breakfast,Long-term stays allowed,Unavail...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",...,9103,Uganda,1,2,2,0,1,0,After 3 00 pm,NaN
12803,8006146,WisDOME - Mentigi Bay Village - Gilis - Lombok,4.86,7,Cempaka,718423.0,"Gunung Sari, Nusa Tenggara Barat, Indonesia","8 guests,2 bedrooms,4 beds,2.5 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,42262,Indonesia,2,4,8,0,2,0,Flexible,12 00 pm
12804,40547903,Enjoy Vitamin SEA! Ocean Front! [Ocean's Seven],4.85,13,Achy,246470880.0,"Uruma, Okinawa, Japan","5 guests,1 bedroom,2 beds,1 bathroom","Sea view,Beach access – Beachfront,Kitchen,Wif...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,S...",...,9909,Japan,1,2,5,0,1,0,After 4 00 pm,11 00 am

# ID

In [84]:
len(df['address'])

12805

In [85]:
df['id'].nunique()

12805

# Name

In [86]:
df['name'].value_counts()

name
Dorm Bed in Traditional Ger - Mongol Ujin Camp                               6
Haveli  - Large room in Art & Book filled mansion!                           5
The goat village Nagtibba By Bakri Chhap                                     4
InnerX-Stay, Floating Homestay in Lan Ha bay                                 4
Comfort room with breakfast included                                         3
                                                                            ..
Lalie Guest House - Complete House                                           1
✿Surfer's Dream✿                                                             1
Stunning modern 3 bedroom apartment in Netanya with spectacular sea views    1
Green Garden                                                                 1
Charming & comfortable bungalow                                              1
Name: count, Length: 12716, dtype: int64

In [87]:
df['name'].nunique()

12716

# Rating

In [88]:
df[df['rating'] == 'New']

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,...,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,4665,Turkey,2,2,4,0,2,0,4 00 pm - 11 00 pm,10 00 am
4,51245886,Bungalov Ev 2,New,0,Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,6673,Turkey,1,1,2,0,1,0,After 2 00 pm,12 00 pm
5,48650769,CasaMia White Suite Treehouse,New,0,Casamia,261290482.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,2 beds,1 bathroom","Lake view,Mountain view,Waterfront,Wifi,Dedica...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",...,14729,Turkey,1,2,2,0,1,0,After 2 00 pm,12 00 pm
6,50765985,Ladin Bungalow,New,0,Stephen,15084529.0,"Kaş, Antalya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Garden view,Mountain view,Kitchen,Wifi,Dedicat...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,12312,Turkey,1,1,2,0,1,0,After 3 00 pm,11 00 am
7,40947216,Lavender House,New,0,Caner,318794897.0,"Akçalı, Giresun, Turkey","8 guests,1 bedroom,2 beds,1 bathroom","Wifi,Dedicated workspace,Free parking on premi...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,13655,Turkey,1,2,8,0,1,0,Flexible,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12790,53925646,Dome2 Rooms Dome2 in a home where you can esca...,New,1,Onda,331826286.0,"Nam-myeon, Jeongseon-gun, Gangwon Province, So...","5 guests,1 bedroom,1 bathroom","Waterfront,Kitchen,Wifi,Free parking on premis...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,4980,South Korea,1,0,5,0,1,0,3 00 pm - 10 00 pm,11 00 am
12791,41257160,Romantic stay at Tent galaxy villa with jacuzzi,New,1,Pt. Archi,110392424.0,"Kecamatan Kuta Selatan, Bali, Indonesia","2 guests,1 bedroom,1 bed,1 bathroom","Wifi,Free parking on premises,Private pool,Pet...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,10729,Indonesia,1,1,2,0,1,0,After 2 00 pm,NaN
12793,621201623913222432,Kintamani Glamping Black Lava camp Potato 2,New,0,Black Lava Camp,454606239.0,"Kintamani, Bali, Indonesia","2 guests,1 bedroom,1 bed,Shared toilet with sink","Free parking on premises,Pool,Fire pit,Long-te...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,3428,Indonesia,0,1,2,1,1,0,After 3 00 pm,NaN
12795,44045739,Tambu a mare,New,0,Maria,122986750.0,"Augusta, Sicilia, Italy","5 guests,1 bedroom,2 beds,1.5 bathrooms","Beach access – Beachfront,Kitchen,Wifi,Dedicat...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",...,8841,Italy,1,2,5,0,1,0,1 00 pm - 8 00 pm,11 00 am
12799,640474109823176234,"Holiday home, Plemmirio",New,0,Daphne Belvilla,385223440.0,"Syracuse, Sicilia, Italy","8 guests,4 bedrooms,4 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free on-stree...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,20311,Italy,2,4,8,0,4,0,2 00 pm - 8 00 pm,10 00 am

In [89]:
## Replace
df[df['rating'] == 'New'].replace('New', 0)

/tmp/ipython-input-418869289.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[df['rating'] == 'New'].replace('New', 0)

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,...,price,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout
1,50891766,Authentic Beach Architect Sheltered Villa with...,0,0,Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,4665,Turkey,2,2,4,0,2,0,4 00 pm - 11 00 pm,10 00 am
4,51245886,Bungalov Ev 2,0,0,Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,6673,Turkey,1,1,2,0,1,0,After 2 00 pm,12 00 pm
5,48650769,CasaMia White Suite Treehouse,0,0,Casamia,261290482.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,2 beds,1 bathroom","Lake view,Mountain view,Waterfront,Wifi,Dedica...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",...,14729,Turkey,1,2,2,0,1,0,After 2 00 pm,12 00 pm
6,50765985,Ladin Bungalow,0,0,Stephen,15084529.0,"Kaş, Antalya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Garden view,Mountain view,Kitchen,Wifi,Dedicat...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,12312,Turkey,1,1,2,0,1,0,After 3 00 pm,11 00 am
7,40947216,Lavender House,0,0,Caner,318794897.0,"Akçalı, Giresun, Turkey","8 guests,1 bedroom,2 beds,1 bathroom","Wifi,Dedicated workspace,Free parking on premi...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,13655,Turkey,1,2,8,0,1,0,Flexible,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12790,53925646,Dome2 Rooms Dome2 in a home where you can esca...,0,1,Onda,331826286.0,"Nam-myeon, Jeongseon-gun, Gangwon Province, So...","5 guests,1 bedroom,1 bathroom","Waterfront,Kitchen,Wifi,Free parking on premis...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,4980,South Korea,1,0,5,0,1,0,3 00 pm - 10 00 pm,11 00 am
12791,41257160,Romantic stay at Tent galaxy villa with jacuzzi,0,1,Pt. Archi,110392424.0,"Kecamatan Kuta Selatan, Bali, Indonesia","2 guests,1 bedroom,1 bed,1 bathroom","Wifi,Free parking on premises,Private pool,Pet...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,10729,Indonesia,1,1,2,0,1,0,After 2 00 pm,NaN
12793,621201623913222432,Kintamani Glamping Black Lava camp Potato 2,0,0,Black Lava Camp,454606239.0,"Kintamani, Bali, Indonesia","2 guests,1 bedroom,1 bed,Shared toilet with sink","Free parking on premises,Pool,Fire pit,Long-te...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,3428,Indonesia,0,1,2,1,1,0,After 3 00 pm,NaN
12795,44045739,Tambu a mare,0,0,Maria,122986750.0,"Augusta, Sicilia, Italy","5 guests,1 bedroom,2 beds,1.5 bathrooms","Beach access – Beachfront,Kitchen,Wifi,Dedicat...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",...,8841,Italy,1,2,5,0,1,0,1 00 pm - 8 00 pm,11 00 am
12799,640474109823176234,"Holiday home, Plemmirio",0,0,Daphne Belvilla,385223440.0,"Syracuse, Sicilia, Italy","8 guests,4 bedrooms,4 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free on-stree...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,20311,Italy,2,4,8,0,4,0,2 00 pm - 8 00 pm,10 00 am

In [90]:
## Creating a new data framing for removing the values which doesnot have
## 'new' in them and putting those values in new dataframe.
df_= df[df['rating'] != 'New']

In [91]:
## reseting the index means the numbering which so it is shown constant without
## missig numbers.
df_.reset_index(inplace = True)

In [92]:
df['rating'].unique()

array(['4.71', 'New', '4.85', '5.0', '4.67', '4.97', '4.89', '4.83',
       '4.87', '4.9', '4.75', '4.76', '4.84', '4.79', '4.82', '4.93',
       '4.96', '4.6', '4.64', '4.68', '4.8', '4.69', '4.58', '4.63',
       '4.91', '4.88', '4.94', '4.92', '4.86', '4.78', '4.57', '4.99',
       '4.98', '4.74', '4.7', '4.77', '4.72', '4.73', '4.95', '4.81',
       '4.53', '4.59', '4.62', '4.61', '4.51', '4.54', '4.56', '4.65',
       '4.55', '4.66', '4.52', '4.5', '4.33', '4.26', '3.33', '4.2',
       '4.0', '4.48', '4.38', '3.0', '4.49', '4.28', '4.45', '4.25',
       '4.36', '4.46', '4.44', '4.43', '3.75', '3.25', '4.13', '4.15',
       '3.88', '4.29', '4.4', '3.5', '4.31'], dtype=object)

In [93]:
# the values were in string or were as object, so in this we changed the type
# from string to float
df['rating'] = df['rating'].replace('New', np.nan)
df['rating'] = df['rating'].astype(float)

In [94]:
df['rating'].mean()

np.float64(4.857475195517684)

In [95]:
## To find the countries
for i in df['country'].unique():
  print(i)

 Turkey
 Georgia
 Vietnam
 Thailand
 South Korea
 India
 Philippines
 Japan
 Lebanon
 Taiwan
 Israel
Turkey
 Armenia
 Cyprus
 Lithuania
 Slovakia
 Denmark
 Germany
 Indonesia
 Poland
 Romania
 Greece
 Ukraine
 Hungary
 Albania
 Bulgaria
 Malaysia
 Montenegro
 Slovenia
 Czechia
 Sweden
 Austria
 Croatia
 Tanzania
 Italy
 Sri Lanka
Philippines
 Bosnia & Herzegovina
Montenegro
 Kenya
 Serbia
 Seychelles
 Finland
 Norway
 Iceland
 Greenland
 United States
 Canada
 Svalbard & Jan Mayen
Iceland
 France
 Australia
 Morocco
 Egypt
 South Africa
 Spain
 United Arab Emirates
 United Kingdom
 Pakistan
Thailand
 Nepal
Sri Lanka
 Singapore
 Cambodia
 Azerbaijan
 Estonia
 Latvia
 Costa Rica
 Netherlands
 Portugal
 New Zealand
 Panama
 Mexico
 Peru
 Chile
 Belize
Panama
 Colombia
 Switzerland
 Ireland
 Bolivia
India
United Kingdom
 Belgium
 Brazil
 Mauritius
 Fiji
 Maldives
Serbia
 Hong Kong
 Myanmar
Malaysia
 Brunei
Italy
 Kyrgyzstan
 Puerto Rico
 Uruguay
 Argentina
 Bahamas
 Oman
 Kuwait
 Saudi Arabia
 Kazakhstan
 Uganda
Maldives
 Qatar
 Jordan
Egypt
 Bangladesh
 Mongolia
 Uzbekistan
Israel
 Liechtenstein
 Rwanda
 Honduras
 Nicaragua
 Vanuatu
Belize
 Cayman Islands
 French Polynesia
 Jamaica
Isle of Man
 Guadeloupe
 Madagascar
Jordan
Bulgaria
Georgia
Japan
Greece
Portugal
Taiwan
Saudi Arabia
Norway
 Åland Islands
Latvia
 Malta
 Tunisia
 Congo
 Cuba
Cuba
 Nigeria
 Kosovo
 St Martin
 Guatemala
 Senegal
Puerto Rico
Morocco
 Namibia

In [96]:
# Trim is called Strip in Python
# To remove the unnecessary spaces
df['cleaned_country'] = df['country'].str.strip()

In [97]:
df

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,...,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout,cleaned_country
0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",...,Turkey,1,1,2,0,2,0,Flexible,12 00 pm,Turkey
1,50891766,Authentic Beach Architect Sheltered Villa with...,NaN,0,Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,Turkey,2,2,4,0,2,0,4 00 pm - 11 00 pm,10 00 am,Turkey
2,50699164,cottages sataplia,4.85,68,Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",...,Georgia,1,3,4,0,1,0,After 1 00 pm,12 00 pm,Georgia
3,49871422,Sapanca Breathable Bungalow,5.00,13,Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",...,Turkey,1,2,4,0,1,0,After 2 00 pm,12 00 pm,Turkey
4,51245886,Bungalov Ev 2,NaN,0,Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,Turkey,1,1,2,0,1,0,After 2 00 pm,12 00 pm,Turkey
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12800,44697740,"Brown Dome House No. 3, full of healing",4.94,16,Aidan,161552316.0,"Imhoe-myeon, Jindo, South Jeolla Province, Sou...","4 guests,8 bathrooms","Kitchen,Wifi,Free parking on premises,Private ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠁,C...",...,South Korea,8,0,4,0,0,0,3 00 pm - 11 00 pm,11 00 am,South Korea
12801,29975283,Bubble Hotel Ubud with Bathtub under the Sky,4.67,6,Martha,118954227.0,"Gianyar, Indonesia","2 guests,1 bedroom,1 bed,Toilet with sink","Wifi,Free on-street parking,Air conditioning,G...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,Indonesia,0,1,2,1,1,0,3 00 pm - 10 00 pm,12 00 pm,Indonesia
12802,32977697,Paradise Eco Hub,4.67,3,Silas,175214568.0,"Kabale, Uganda","2 guests,1 bedroom,2 beds,1 private bathroom","Wifi,Breakfast,Long-term stays allowed,Unavail...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",...,Uganda,1,2,2,0,1,0,After 3 00 pm,NaN,Uganda
12803,8006146,WisDOME - Mentigi Bay Village - Gilis - Lombok,4.86,7,Cempaka,718423.0,"Gunung Sari, Nusa Tenggara Barat, Indonesia","8 guests,2 bedrooms,4 beds,2.5 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,Indonesia,2,4,8,0,2,0,Flexible,12 00 pm,Indonesia
12804,40547903,Enjoy Vitamin SEA! Ocean Front! [Ocean's Seven],4.85,13,Achy,246470880.0,"Uruma, Okinawa, Japan","5 guests,1 bedroom,2 beds,1 bathroom","Sea view,Beach access – Beachfront,Kitchen,Wif...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,S...",...,Japan,1,2,5,0,1,0,After 4 00 pm,11 00 am,Japan

In [98]:
df[df['cleaned_country'] == 'Japan']

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,...,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout,cleaned_country
39,21082489,LOGIN OKINAWA -wood-,4.68,241,LoginOkinawa,151975076.0,"Onna-son, Kunigami-gun, Okinawa-ken, Japan","9 guests,3 bedrooms,7 beds,1 bathroom","Resort view,Ocean view,Beach access – Beachfro...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",...,Japan,1,7,9,0,3,0,4 00 pm - 12 00 am,11 00 am,Japan
51,679805160588663838,LOGIN OKINAWA -plants-,NaN,0,LoginOkinawa,151975076.0,"Onna, Kunigami District, Okinawa, Japan","8 guests,3 bedrooms,6 beds,1 bathroom","Beach access,Kitchen,Wifi,Dedicated workspace,...","󹀁,Airbnb's COVID-19 safety practices apply,Car...",...,Japan,1,6,8,0,3,0,After 4 00 pm,11 00 am,Japan
54,34029409,恩纳村的打卡圣地网红海景小木屋Cinderella J House,4.58,58,Kiyomi,247159295.0,"Onna, Kunigami-gun, Okinawa, Japan","8 guests,3 bedrooms,4 beds,1 bathroom","Garden view,Beach access,Kitchen,Wifi,Dedicate...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,S...",...,Japan,1,4,8,0,3,0,After 4 00 pm,11 00 am,Japan
1191,3209511,Beach Side House alohana,4.99,249,Miki&Masa,10312136.0,"Ishigaki, Okinawa Prefecture, Japan","2 guests,1 bedroom,2 beds,1 bathroom","Garden view,Beach access,Wifi,Dedicated worksp...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",...,Japan,1,2,2,0,1,0,3 00 pm - 9 00 pm,11 00 am,Japan
1204,19256665,A small house in the forest / Relaxing environ...,4.64,173,Daisuke,23602769.0,"Nishi-ku, Fukuoka-shi, Fukuoka-ken, Japan","2 guests,1 bedroom,2 beds,1 bathroom","Courtyard view,Kitchen,Wifi,Free parking on pr...","󹀁,Airbnb's COVID-19 safety practices apply,Car...",...,Japan,1,2,2,0,1,0,3 00 pm - 2 00 am,10 00 am,Japan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12745,585129042504781524,"URUMA DOME Earth4 & Mars5 MK309,310",4.67,12,Hiro,374017994.0,"Uruma, Okinawa, Japan","4 guests,1 bedroom,2 beds,1 bathroom","Waterfront,Kitchen,Wifi,Free parking on premis...","󹀁,Airbnb's COVID-19 safety practices apply,Car...",...,Japan,1,2,4,0,1,0,After 4 00 pm,11 00 am,Japan
12761,49630137,Comfort Privacy and Nature with a View. Pets OK!,4.86,7,Stephane,400278563.0,"Yuzawa, Minamiuonuma District, Niigata, Japan","3 guests,1 bedroom,2 beds,Toilet with sink","Mountain view,Public or shared beach access,Ki...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",...,Japan,0,2,3,1,1,0,After 3 00 pm,11 00 am,Japan
12788,43681892,Enjoy Vitamin SEA! Ocean Front! [Ocean's Seven2],4.95,21,Achy,246470880.0,"Uruma, Okinawa, Japan","4 guests,1 bedroom,2 beds,1 bathroom","Ocean view,Sea view,Beach access – Beachfront,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,S...",...,Japan,1,2,4,0,1,0,After 4 00 pm,11 00 am,Japan
12797,44080105,Enjoy Vitamin SEA! Ocean Front! [Ocean's Seve...,5.00,6,Achy,246470880.0,"Uruma, Okinawa, Japan","4 guests,1 bedroom,3 beds,1 bathroom","Ocean view,Sea view,Beach access,Kitchen,Wifi,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",...,Japan,1,3,4,0,1,0,After 4 00 pm,11 00 am,Japan
12804,40547903,Enjoy Vitamin SEA! Ocean Front! [Ocean's Seven],4.85,13,Achy,246470880.0,"Uruma, Okinawa, Japan","5 guests,1 bedroom,2 beds,1 bathroom","Sea view,Beach access – Beachfront,Kitchen,Wif...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,S...",...,Japan,1,2,5,0,1,0,After 4 00 pm,11 00 am,Japan

In [99]:
df['address'].str.split(',').str[-2].str.strip()

0                      Kocaeli
1                      Antalya
2                      Imereti
3                      Sakarya
4                      Sakarya
                 ...
12800    South Jeolla Province
12801                  Gianyar
12802                   Kabale
12803      Nusa Tenggara Barat
12804                  Okinawa
Name: address, Length: 12805, dtype: object

In [100]:
japan_df = df[(df['cleaned_country'] == 'Japan') & (df['bedrooms'] > 1)]
display(japan_df.head(5)['host_name'])

39      LoginOkinawa
51      LoginOkinawa
54            Kiyomi
1226           Saori
1229           Keiko
Name: host_name, dtype: object

In [101]:
## Count of the countries
for i in df['cleaned_country'].unique():
  print(i, len(df[df['cleaned_country'] == i]))

Turkey 522
Georgia 371
Vietnam 103
Thailand 683
South Korea 226
India 2779
Philippines 199
Japan 322
Lebanon 23
Taiwan 312
Israel 137
Armenia 6
Cyprus 20
Lithuania 25
Slovakia 14
Denmark 29
Germany 261
Indonesia 262
Poland 134
Romania 108
Greece 889
Ukraine 42
Hungary 27
Albania 4
Bulgaria 53
Malaysia 105
Montenegro 12
Slovenia 36
Czechia 60
Sweden 150
Austria 63
Croatia 145
Tanzania 8
Italy 1187
Sri Lanka 275
Bosnia & Herzegovina 6
Kenya 56
Serbia 56
Seychelles 9
Finland 138
Norway 211
Iceland 34
Greenland 1
United States 191
Canada 37
Svalbard & Jan Mayen 1
France 466
Australia 25
Morocco 377
Egypt 70
South Africa 39
Spain 66
United Arab Emirates 52
United Kingdom 313
Pakistan 11
Nepal 38
Singapore 5
Cambodia 19
Azerbaijan 4
Estonia 40
Latvia 21
Costa Rica 4
Netherlands 97
Portugal 44
New Zealand 7
Panama 13
Mexico 25
Peru 4
Chile 8
Belize 14
Colombia 13
Switzerland 49
Ireland 6
Bolivia 1
Belgium 40
Brazil 18
Mauritius 5
Fiji 2
Maldives 41
Hong Kong 6
Myanmar 2
Brunei 2
Kyrgyzstan 25
Puerto Rico 4
Uruguay 2
Argentina 3
Bahamas 2
Oman 10
Kuwait 2
Saudi Arabia 3
Kazakhstan 6
Uganda 7
Qatar 2
Jordan 94
Bangladesh 3
Mongolia 60
Uzbekistan 2
Liechtenstein 1
Rwanda 2
Honduras 2
Nicaragua 6
Vanuatu 1
Cayman Islands 2
French Polynesia 6
Jamaica 2
Isle of Man 1
Guadeloupe 2
Madagascar 3
Åland Islands 1
Malta 6
Tunisia 2
Congo 1
Cuba 255
Nigeria 1
Kosovo 1
St Martin 1
Guatemala 1
Senegal 1
Namibia 3

In [102]:
df['bathrooms'].value_counts()

bathrooms
1     8000
2     1917
3      902
4      590
0      446
5      306
6      215
8      121
7      106
9       50
10      40
12      27
11      22
13      16
14       9
15       8
21       4
17       4
24       4
22       3
18       3
16       3
50       2
23       2
38       1
27       1
25       1
30       1
20       1
Name: count, dtype: int64

In [103]:
df[df['bathrooms'] == 50]

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,...,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout,cleaned_country
1111,47891864,Inn resort garden house,NaN,1,Chindanai,321081514.0,"Ban Luang, Chang Wat Chiang Mai, Thailand","16 guests,50 bedrooms,2 beds,50 bathrooms","Wifi,Free parking on premises,Pets allowed,TV,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,Thailand,50,2,16,0,50,0,2 00 pm - 10 00 pm,NaN,Thailand
4351,15217006,Classic Tour Services Nile Cruise booking,NaN,0,Hatem,96686906.0,"Luxor , Luxor Governorate, Egypt","16 guests,50 bedrooms,50 beds,50 bathrooms","Kitchen,Wifi,Free parking on premises,Pool,Sha...","󹀁,Airbnb's COVID-19 safety practices apply,Car...",...,Egypt,50,50,16,0,50,0,11 00 am - 1 00 pm,NaN,Egypt

In [104]:
for i in df['bathrooms'].unique():
  print(i, len(df[df['bathrooms'] == i]))

1 8000
2 1917
3 902
4 590
0 446
5 306
6 215
8 121
7 106
9 50
10 40
50 2
12 27
24 4
17 4
21 4
11 22
18 3
16 3
38 1
13 16
27 1
25 1
15 8
23 2
14 9
22 3
30 1
20 1

# Reviews

In [105]:
df['reviews'].value_counts()

reviews
0      2393
1      1131
2       707
3       464
4       324
       ...
524       1
257       1
510       1
359       1
267       1
Name: count, Length: 409, dtype: int64

In [106]:
# Check for non-integer values in 'reviews' column
non_int_reviews = df[~df['reviews'].str.isdigit()]['reviews'].unique()
if len(non_int_reviews) > 0:
    print(f"Found non-integer values in 'reviews': {non_int_reviews}")
    # Decide how to handle these values, e.g., replace with NaN or drop rows
    # For now, I'll print them and stop the conversion.
else:
    df['reviews'] = df['reviews'].astype(int)
    print("'reviews' column converted to integer type.")

Found non-integer values in 'reviews': ['1,003']

In [108]:
df['reviews'] = df['reviews'].astype(str)
df['reviews'] = df['reviews'].str.replace(',', '')
df['reviews'] = df['reviews'].astype(int)

In [109]:
df['reviews'].mean()

np.float64(36.1400234283483)

# Features

In [110]:
df['features']

0                2 guests,2 bedrooms,1 bed,1 bathroom
1              4 guests,2 bedrooms,2 beds,2 bathrooms
2                4 guests,1 bedroom,3 beds,1 bathroom
3                4 guests,1 bedroom,2 beds,1 bathroom
4                 2 guests,1 bedroom,1 bed,1 bathroom
                             ...
12800                            4 guests,8 bathrooms
12801       2 guests,1 bedroom,1 bed,Toilet with sink
12802    2 guests,1 bedroom,2 beds,1 private bathroom
12803        8 guests,2 bedrooms,4 beds,2.5 bathrooms
12804            5 guests,1 bedroom,2 beds,1 bathroom
Name: features, Length: 12805, dtype: object

In [112]:
# df[df['features'].str.split(',').str.len() == 2]
# or
df[df['features'].str.split(',').str.len() == 4]['features']

0                2 guests,2 bedrooms,1 bed,1 bathroom
1              4 guests,2 bedrooms,2 beds,2 bathrooms
2                4 guests,1 bedroom,3 beds,1 bathroom
3                4 guests,1 bedroom,2 beds,1 bathroom
4                 2 guests,1 bedroom,1 bed,1 bathroom
                             ...
12799          8 guests,4 bedrooms,4 beds,2 bathrooms
12801       2 guests,1 bedroom,1 bed,Toilet with sink
12802    2 guests,1 bedroom,2 beds,1 private bathroom
12803        8 guests,2 bedrooms,4 beds,2.5 bathrooms
12804            5 guests,1 bedroom,2 beds,1 bathroom
Name: features, Length: 12155, dtype: object

In [114]:
df.columns

Index(['id', 'name', 'rating', 'reviews', 'host_name', 'host_id', 'address',
       'features', 'amenities', 'safety_rules', 'hourse_rules', 'img_links',
       'price', 'country', 'bathrooms', 'beds', 'guests', 'toiles', 'bedrooms',
       'studios', 'checkin', 'checkout', 'cleaned_country'],
      dtype='object')

# Amenities

In [115]:
df['amenities']

0        Mountain view,Valley view,Lake access,Kitchen,...
1        Kitchen,Wifi,Dedicated workspace,Free parking ...
2        Mountain view,Kitchen,Wifi,Dedicated workspace...
3        Mountain view,Valley view,Kitchen,Wifi,Free pa...
4        Kitchen,Wifi,Free parking on premises,TV,Air c...
                               ...
12800    Kitchen,Wifi,Free parking on premises,Private ...
12801    Wifi,Free on-street parking,Air conditioning,G...
12802    Wifi,Breakfast,Long-term stays allowed,Unavail...
12803    Kitchen,Wifi,Dedicated workspace,Free parking ...
12804    Sea view,Beach access – Beachfront,Kitchen,Wif...
Name: amenities, Length: 12805, dtype: object

In [117]:
# df[df['amenities'].str.split(',').str.len() == 2]
# or
df[df['amenities'].str.split(',').str.len() == 3]['amenities']

741      Long-term stays allowed,Unavailable: Carbon mo...
1138     Long-term stays allowed,Unavailable: Carbon mo...
1219     Long-term stays allowed,Unavailable: Carbon mo...
1345     Free parking on premises,Long-term stays allow...
1515     Free parking on premises,Air conditioning,Long...
2567     Long-term stays allowed,Unavailable: Carbon mo...
2928               Wifi,Hair dryer,Long-term stays allowed
2985     Free parking on premises,Shared pool,Long-term...
3052     Free parking on premises,Long-term stays allow...
3709     Long-term stays allowed,Unavailable: Carbon mo...
3949     Long-term stays allowed,Unavailable: Carbon mo...
4359     Kitchen,Long-term stays allowed,Unavailable: C...
4393     Long-term stays allowed,Unavailable: Carbon mo...
4424     Long-term stays allowed,Unavailable: Carbon mo...
4455     Air conditioning,Long-term stays allowed,Unava...
4497     Long-term stays allowed,Unavailable: Carbon mo...
4524     Long-term stays allowed,Unavailable: Carbon mo...
4620     Long-term stays allowed,Unavailable: Carbon mo...
4935     Pets allowed,Unavailable: Carbon monoxide alar...
5760     Kitchen,Long-term stays allowed,Unavailable: C...
6026     Long-term stays allowed,Unavailable: Carbon mo...
6170     Long-term stays allowed,Unavailable: Carbon mo...
6347     Long-term stays allowed,Unavailable: Carbon mo...
6769     Long-term stays allowed,Unavailable: Carbon mo...
7623     Long-term stays allowed,Unavailable: Carbon mo...
7629     Long-term stays allowed,Unavailable: Carbon mo...
7697     Long-term stays allowed,Unavailable: Carbon mo...
7824     Long-term stays allowed,Unavailable: Carbon mo...
8382                Free on-street parking,Garden,Fire pit
8396     Washing machine,Unavailable: Carbon monoxide a...
8707     Long-term stays allowed,Unavailable: Carbon mo...
8732     Long-term stays allowed,Unavailable: Carbon mo...
9535     Kitchen,Unavailable: Carbon monoxide alarmCarb...
9695     Long-term stays allowed,Unavailable: Carbon mo...
9707     Long-term stays allowed,Unavailable: Carbon mo...
9724     Long-term stays allowed,Unavailable: Carbon mo...
9733     Long-term stays allowed,Unavailable: Carbon mo...
9753     Long-term stays allowed,Unavailable: Carbon mo...
9774     Free parking on premises,Long-term stays allow...
9784     Kitchen,Long-term stays allowed,Unavailable: C...
9803     Pets allowed,Unavailable: Carbon monoxide alar...
9848     Long-term stays allowed,Unavailable: Carbon mo...
10851    Wifi,Dedicated workspace,Unavailable: Carbon m...
11726    Kitchen,Long-term stays allowed,Unavailable: C...
12071    Kitchen,Indoor fireplace,Unavailable: Carbon m...
12245    Dedicated workspace,Breakfast,Unavailable: Car...
Name: amenities, dtype: object

In [119]:
## There is a spelling mistake in the one of the columns.
df[df['hourse_rules'].str.split(',').str.len() == 2]

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,...,country,bathrooms,beds,guests,toiles,bedrooms,studios,checkin,checkout,cleaned_country
32,50458442,Bungalow Holiday Villa Gen with Private Pool a...,4.64,11,Fatih,386223873.0,"Kaş, Antalya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,Turkey,1,1,2,0,1,0,4 00 pm - 11 00 pm,10 00 am,Turkey
63,636562135731372477,4-Person Villa with Nature View,NaN,0,Muhammet,107878101.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,3 beds,2 bathrooms","Kitchen,Wifi,Free parking on premises,Pool,Hot...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,Turkey,2,3,4,0,2,0,After 4 00 pm,10 00 am,Turkey
82,562138091801957973,Sleeps 2 with a private pool and a jacuzzi in ...,NaN,1,Gülcan,445030155.0,"Kaş, Antalya, Turkey","2 guests,1 bedroom,1 bed,1.5 bathrooms","Mountain view,Kitchen,Wifi,Dedicated workspace...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,Turkey,1,1,2,0,1,0,After 3 00 pm,NaN,Turkey
91,51120664,HAERI • (H1) • Utsera Cabins • Racha,5.00,3,Geno,201241578.0,"Oni, Racha-Lechkhumi and Kvemo Svaneti, Georgia","4 guests,1 bedroom,2 beds,1 bathroom","Kitchen,Wifi,Free on-street parking,Free washi...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,Georgia,1,2,4,0,1,0,After 2 00 pm,12 00 am,Georgia
103,618591377457733542,Enjoying a peaceful vacation is personal,NaN,0,Kenan,432147856.0,"Kaş, Antalya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,Pool,Hot...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,Turkey,1,1,2,0,1,0,11 00 am - 12 00 am,11 00 am,Turkey
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12714,632555985266496734,Small geodesic forest dome for two people,4.64,24,Alen,419504339.0,"Lupoglav, Istria County, Croatia","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free driveway parking on premises...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,Croatia,1,1,2,0,1,0,After 4 00 pm,12 00 pm,Croatia
12718,579492879082561857,Adorable A/c Luxury Geodesic Dome with a Dip ...,NaN,0,Sibi,384477078.0,"Karimkunnam, Kerala, India","4 guests,1 bedroom,2 beds,1 private bathroom","Wifi,Dedicated workspace,Free parking on premi...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",...,India,1,2,4,0,1,0,After 12 00 pm,NaN,India
12720,617961142341439818,Nature habitat - room in nature - One,NaN,0,Bojan,64470912.0,"Vrh, Primorsko-goranska županija, Croatia","3 guests,1 bed,5 bathrooms","Wifi,Hot tub,TV,Fire pit,Long-term stays allow...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,Croatia,5,1,3,0,0,0,After 3 00 pm,10 00 am,Croatia
12726,47730398,Følvika Eagle Eye,4.96,47,Lill Hilde,220513971.0,"Gildeskål, Nordland, Norway","2 guests,1 bedroom,1 bed,Toilet with sink","Waterfront,Free parking on premises,Pets allow...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",...,Norway,0,1,2,1,1,0,Flexible,NaN,Norway
12744,579509532534384214,Breezy hill top Bubble House with a Dip Pool,NaN,0,Sibi,384477078.0,"Karimkunnam, Kerala, India","2 guests,1 bedroom,2 beds,1 private bathroom","Wifi,Dedicated workspace,Free parking on premi...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",...,India,1,2,2,0,1,0,After 12 00 pm,NaN,India